AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ElasticBeanstalkApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: graduate-admission-predictor
      Description: "Graduate Admission Predictor Flask Application"

  ElasticBeanstalkEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref ElasticBeanstalkApplication
      EnvironmentName: graduate-admission-env
      SolutionStackName: "64bit Amazon Linux 2023 v4.3.0 running Python 3.8"
      OptionSettings:
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: FLASK_ENV
          Value: production
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: t3.small
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: SingleInstance
      Tags:
        - Key: Project
          Value: graduate-admission-predictor